tasks:
  - init: ./mvnw install -DskipTests=false

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - redhat.vscode-quarkus
    - redhat.vscode-commons
    - redhat.vscode-microprofile
